version: "3"

services:
  workzone:
    image: skeleton-vuecli:env
    command: "vue ui --host 0.0.0.0 --port 8000 --headless"
    env_file: 
      - app.env
    volumes:
      - ./frontend:/opt/webapp
    ports:
      - 8000
      - 8080
